# Generated by Django 5.2 on 2025-04-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='faixa_etaria',
            field=models.CharField(choices=[('infantil', 'Infantil'), ('juvenil', 'Juvenil'), ('juvenil1', 'Juvenil1'), ('adulto', 'Adulto')], default='adulto', max_length=10),
        ),
    ]
