# Generated by Django 5.2 on 2025-04-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_faixa_etaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='faixa_etaria',
        ),
    ]
