# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professores', '0001_initial'),
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('licao_dada', models.TextField(blank=True, null=True)),
                ('alunos', models.ManyToManyField(blank=True, to='alunos.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professores.professor')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['-data'],
            },
        ),
    ]
