# Generated by Django 5.2 on 2025-04-11 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_alter_membros_cargo'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='professor',
            field=models.ForeignKey(limit_choices_to=models.Q(('cargo__in', ['Pastor', 'Presbítero', 'Diácono'])), on_delete=django.db.models.deletion.PROTECT, to='membros.membros'),
        ),
    ]
