# Generated by Django 4.2.3 on 2025-04-11 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_alter_membros_cargo'),
        ('salas', '0004_alter_salas_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='alunos',
            field=models.ManyToManyField(help_text='Selecione os alunos (apenas membros ativos)', limit_choices_to={'cargo': 'Membro Ativo'}, related_name='salas_como_aluno', to='membros.membros'),
        ),
        migrations.AlterField(
            model_name='salas',
            name='professor',
            field=models.ForeignKey(limit_choices_to=models.Q(('cargo__in', ['Pastor', 'Presbítero', 'Professor']), ('cargo', 'Membro Ativo'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to='membros.membros'),
        ),
    ]
