# Generated by Django 5.2 on 2025-04-12 00:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('professores', '0001_initial'),
        ('salas', '0005_alter_salas_alunos_alter_salas_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='salas',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='alunos.aluno'),
        ),
        migrations.AlterField(
            model_name='salas',
            name='licao_dada',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salas',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='professores.professor'),
        ),
    ]
