# Generated by Django 5.2 on 2025-04-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_alter_membros_cargo'),
        ('salas', '0006_remove_salas_tipo_alter_salas_alunos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'cargo__in': ['Professor', 'Presbítero', 'Pastor']}, on_delete=django.db.models.deletion.PROTECT, to='membros.membros'),
        ),
    ]
