# Generated by Django 5.2 on 2025-04-12 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_alter_membros_cargo'),
        ('salas', '0007_alter_salas_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'cargo__in': ['Professor', 'Presbítero', 'Pastor', 'Membro Ativo']}, on_delete=django.db.models.deletion.PROTECT, to='membros.membros'),
        ),
    ]
