# Generated by Django 5.2 on 2025-04-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0008_alter_salas_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='alunos',
        ),
        migrations.AddField(
            model_name='salas',
            name='alunos',
            field=models.TextField(blank=True, help_text='Digite os nomes dos alunos presentes'),
        ),
    ]
