# Generated by Django 5.2 on 2025-04-13 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_faixa_etaria'),
        ('salas', '0009_remove_salas_alunos_salas_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='alunos',
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.aluno')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.salas')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'unique_together': {('sala', 'aluno')},
            },
        ),
        migrations.AddField(
            model_name='salas',
            name='alunos',
            field=models.ManyToManyField(through='salas.Presenca', to='alunos.aluno'),
        ),
    ]
