# Generated by Django 5.2 on 2025-04-13 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0003_alter_membros_cargo'),
        ('salas', '0010_remove_salas_alunos_presenca_salas_alunos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.membros'),
        ),
        migrations.AlterField(
            model_name='salas',
            name='alunos',
            field=models.ManyToManyField(related_name='salas_como_aluno', through='salas.Presenca', to='membros.membros'),
        ),
        migrations.AlterField(
            model_name='salas',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'cargo__in': ['Professor', 'Presbítero', 'Pastor', 'Membro Ativo']}, on_delete=django.db.models.deletion.PROTECT, related_name='salas_como_professor', to='membros.membros'),
        ),
    ]
