# Generated by Django 5.2 on 2025-04-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0011_alter_presenca_aluno_alter_salas_alunos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='visitantes',
            field=models.TextField(blank=True, help_text='Registre os nomes dos visitantes, um por linha'),
        ),
    ]
