# Generated by Django 5.2 on 2025-04-14 01:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0012_salas_visitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='classe',
            field=models.CharField(choices=[('4 a 6 anos', 'Classe de 4 a 6 anos'), ('7 a 10 anos', 'Classe de 7 a 10 anos'), ('Juniores', 'Classe de Juniores'), ('Adolescentes e Jovens', 'Classe de Adolescentes e Jovens'), ('Casais', 'Classe de Casais'), ('Nova Vida', 'Classe Nova Vida'), ('Adultos', 'Classe de Adultos'), ('Berçário', 'Berçário')], default=django.utils.timezone.now, help_text='Selecione a classe em que o professor estará lecionando', max_length=50, verbose_name='Classe'),
            preserve_default=False,
        ),
    ]
