# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('faixa_etaria', models.CharField(blank=True, choices=[('Infantil', 'Infantil'), ('Juvenil', 'Juvenil'), ('Juvenil1', 'Juvenil1'), ('Adulto', 'Adulto')], max_length=20, null=True)),
                ('estadocivil', models.CharField(blank=True, choices=[('Divorciado(a)', 'Divorciado(a)'), ('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Viúvo(a)', 'Viúvo(a)')], max_length=40, null=True, verbose_name='Estado civil')),
                ('escolaridade', models.CharField(blank=True, choices=[('Ensino fundamental incompleto', 'Ensino fundamental incompleto'), ('Ensino fundamental completo', 'Ensino fundamental completo'), ('Ensino médio incompleto', 'Ensino médio completo'), ('Superior completo (ou graduação)', 'Superior completo (ou graduação)'), ('Superior incompleto (ou graduação)', 'Superior incompleto (ou graduação)')], max_length=70, null=True, verbose_name='Nível de escolaridade')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('data_batismo', models.DateField(blank=True, null=True, verbose_name='Data do batismo')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de recebimento')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('telefone_fixo', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
