# Generated by Django 4.2.3 on 2025-04-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='data_casamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de casamento'),
        ),
    ]
