# Generated by Django 4.2.3 on 2025-04-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_membros_data_casamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='cargo',
            field=models.CharField(choices=[('Pastor', 'Pastor'), ('Presbítero', 'Presbítero'), ('Diácono', 'Diácono'), ('Secretaria', 'Secretaria'), ('Tesoureiro', 'Tesoureiro'), ('Membro Ativo', 'Membro Ativo'), ('Membro Inativo', 'Membro Inativo'), ('Visitante', 'Visitante'), ('Professor', 'Professor')], max_length=100),
        ),
    ]
