# Generated by Django 5.2 on 2025-04-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0004_membros_bairro_membros_cep_membros_cidade_and_more'),
    ]

    operations = [
    ]
