# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, max_length=150, null=True)),
                ('dia_semana', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('descricao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Lição')),
                ('hora_incio', models.TimeField(blank=True, null=True, verbose_name='Horário de íncio')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Horário do fim')),
                ('quant_visitantes', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de visitantes')),
                ('quant_membros', models.IntegerField(blank=True, null=True, verbose_name='Quantidade de membros')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='membros.membros', verbose_name='Líder')),
            ],
        ),
    ]
