# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição da operação')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código da operação')),
                ('tipo_transferencia', models.TextField(choices=[('TED', 'TED'), ('DOC', 'DOC'), ('PIX', 'PIX'), ('Cédula', 'Cédula')], verbose_name='Tipo da transação')),
                ('clc', models.CharField(choices=[('4100', 'Dízimo'), ('4200', 'Oferta'), ('4300', 'Oferta Missionária'), ('4400', 'Repasse Presbitério'), ('4500', 'Receita Financeira'), ('4600', 'Aluguel/Cessão'), ('4900', 'Outras Receitas')], max_length=4, verbose_name='Classe de Custo')),
                ('valor', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membros.membros', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Contribuição',
                'verbose_name_plural': 'Contribuições',
            },
        ),
    ]
