# Generated by Django 5.2 on 2025-04-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuicoes', '0002_alter_contribuicoes_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuicoes',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
    ]
