# Generated by Django 5.2 on 2025-04-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuicoes', '0003_alter_contribuicoes_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuicoes',
            name='descricao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição da operação'),
        ),
    ]
