# Generated by Django 5.2 on 2025-04-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuicoes', '0004_alter_contribuicoes_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuicoes',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor'),
        ),
    ]
