# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da visita')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('filhos', models.CharField(blank=True, max_length=16, null=True, verbose_name='Quantidade de filhos')),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
