# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso_reunioes', models.BooleanField(default=False)),
                ('acesso_celulas', models.BooleanField(default=False)),
                ('acesso_visitantes', models.BooleanField(default=False)),
                ('acesso_membros', models.BooleanField(default=False)),
                ('acesso_financeiro', models.BooleanField(default=False)),
                ('acesso_salas', models.BooleanField(default=False)),
                ('acesso_matriz', models.BooleanField(default=False)),
                ('acesso_missao', models.BooleanField(default=False)),
                ('acesso_usuarios', models.BooleanField(default=False)),
                ('acesso_despesas', models.BooleanField(default=False)),
                ('acesso_contribuicoes', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
