# Generated by Django 4.2.3 on 2025-03-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_usuario'),
        ('usuarios', '0002_create_default_groups'),
    ]

    operations = [
    ]
