# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_missionario', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
