# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presbitero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=200)),
                ('cargo', models.CharField(max_length=100)),
                ('data_ordem', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReuniaoConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presbiteros', models.TextField(max_length=200, null=True, verbose_name='Presença')),
                ('pauta', models.CharField(max_length=100)),
                ('relatorio', models.TextField(verbose_name='Relatório')),
                ('local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReuniaoDiaconos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaconos', models.TextField(max_length=200, null=True, verbose_name='Presença')),
                ('data', models.DateField()),
                ('relatorio', models.TextField(verbose_name='Relatório')),
                ('local', models.CharField(max_length=100)),
                ('pauta', models.TextField()),
            ],
        ),
    ]
