# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz5W2H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=255)),
                ('why', models.TextField()),
                ('who', models.CharField(max_length=255)),
                ('when', models.DateTimeField()),
                ('where', models.CharField(max_length=255)),
                ('how', models.TextField()),
                ('how_much', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='MatrizGUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Problema')),
                ('causa', models.CharField(max_length=100)),
                ('grupo', models.CharField(choices=[('G1', 'Grupo 1'), ('G2', 'Grupo 2'), ('G3', 'Grupo 3'), ('G4', 'Grupo 4')], max_length=2)),
                ('gravidade', models.IntegerField(choices=[(1, '1 - Muito Baixa'), (2, '2 - Baixa'), (3, '3 - Média'), (4, '4 - Alta'), (5, '5 - Muito Alta')])),
                ('urgencia', models.IntegerField(choices=[(1, '1 - Muito Baixa'), (2, '2 - Baixa'), (3, '3 - Média'), (4, '4 - Alta'), (5, '5 - Muito Alta')])),
                ('tendencia', models.IntegerField(choices=[(1, '1 - Muito Baixa'), (2, '2 - Baixa'), (3, '3 - Média'), (4, '4 - Alta'), (5, '5 - Muito Alta')])),
            ],
        ),
    ]
