# Generated by Django 4.2.3 on 2025-03-26 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('tipo', models.CharField(choices=[('Fixa', 'Despesa Fixa'), ('Variável', 'Despesa Variável'), ('Eventual', 'Despesa Eventual')], max_length=10)),
                ('clc', models.CharField(choices=[('5001', 'Côngruas - Pastor'), ('5002', 'Férias + 1/3 - Pastor'), ('5003', 'Décimo Terceiro - Pastor'), ('5004', 'FAP - Pastor'), ('5005', 'INSS - Pastor'), ('5006', 'Moradia - Pastor'), ('5007', 'Assistência Médica - Pastor'), ('5008', 'Transporte - Pastor'), ('5009', 'Outras Despesas Com Pastor'), ('5011', 'Côngruas - Evangelista'), ('5012', 'Férias + 1/3 - Evangelista'), ('5013', 'Décimo Terceiro - Evangelista'), ('5014', 'FAP - Evangelista'), ('5015', 'INSS - Evangelista'), ('5016', 'Moradia - Evangelista'), ('5017', 'Assistência Médica - Evangelista'), ('5018', 'Transporte - Evangelista'), ('5019', 'Outras Despesas Com Evangelista'), ('5021', 'Seminário DNE'), ('5022', 'Moradia e Alimentação - Seminarista'), ('5023', 'Transporte - Seminarista'), ('5029', 'Outras Despesas Com Seminarista'), ('5031', 'Salário - Administrativo'), ('5032', 'Férias + 1/3 - Administrativo'), ('5033', 'Décimo Terceiro - Administrativo'), ('5034', 'FGTS'), ('5035', 'INSS - Administrativo'), ('5036', 'Assistência Médica/Odontológica'), ('5037', 'Outros Encargos'), ('5038', 'Transporte e Alimentação'), ('5039', 'Outras Despesas Com Administrativo'), ('5100', 'Dízimo Supremo Concílio'), ('5110', 'Dízimo Presbitério'), ('5190', 'Outras Despesas Com PRTI e SC'), ('5200', 'Proventos'), ('5210', 'Ofertas'), ('5220', 'Transporte'), ('5230', 'Cesta Básica / Alimentação'), ('5240', 'Hospedagem'), ('5250', 'Eventos e Datas Comemorativas'), ('5260', 'Junta Diaconal'), ('5290', 'Outras Despesas Missões'), ('5300', 'Escola Bíblica Dominical'), ('5310', 'Ministério Infantil'), ('5320', 'Ministério de Jovens e Adolescentes'), ('5330', 'Ministério de Casais'), ('5340', 'Ministério de Homens'), ('5350', 'Ministério de Mulheres'), ('5360', 'Ministério de Células'), ('5370', 'Ministério de Louvor'), ('5390', 'Outras Sociedades'), ('5400', 'Energia Elétrica'), ('5410', 'Água e Esgoto'), ('5420', 'Telefonia e Internet'), ('5430', 'Correios'), ('5440', 'Aluguel de Equipamento'), ('5450', 'Aluguel de Imóvel'), ('5460', 'Aluguel de Veículo'), ('5490', 'Outras Locações e Serviços Públicos'), ('5500', 'Limpeza'), ('5510', 'Manutenção Predial'), ('5520', 'Manutenção Equipamentos'), ('5530', 'Frete/Transporte'), ('5540', 'Contador'), ('5550', 'Reprografia e Publicidade'), ('5590', 'Outros Serviços Contratados'), ('5600', 'Material de Escritório'), ('5610', 'Material de Expediente'), ('5620', 'Material de Limpeza'), ('5630', 'Material Manutenção Predial'), ('5640', 'Material Manutenção Equipamento'), ('5650', 'Combustível'), ('5660', 'Literatura e Publicações'), ('5690', 'Outros Materiais'), ('5700', 'Manutenção de Conta'), ('5710', 'Tarifa Bancária'), ('5720', 'Juros e Multas'), ('5730', 'Outras Despesas Financeiras'), ('5800', 'Móveis e Utensílios'), ('5810', 'Sonorização e Instrumentos'), ('5820', 'Máquinas e Equipamentos'), ('5830', 'Veículos'), ('5840', 'Imóveis'), ('5850', 'Construções e Benfeitorias'), ('5890', 'Outros Imobilizados')], max_length=4, verbose_name='Classe de Custo')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('PIX', 'PIX'), ('Cartão Débito', 'Cartão Débito'), ('Cartão Crédito', 'Cartão Crédito'), ('Transferência', 'Transferência')], max_length=20, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago'), ('Atrasado', 'Atrasado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=10)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/despesas/')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
